### Configuration for Core Plugin ###

# DO NOT CHANGE THIS! #
Config for minecraft version: 1.21.11

# --- Features --- #

# Character limit you can put in /nick. Players with "cp.nick.bypasslimit" will be ignored.
nick-character-limit: 16
# The color codes will be ignored in character-limit.
ignore-color-codes: false
# Adds a prefix when a player change their nickname. Players with "cp.nick.hideprefix" won't have this prefix.
nickname-prefix: '*'

# Add cooldown to prevent players to spam the command. Players with "cp.afk.bypasscooldown" will be ignored.
afk-cooldown: 30
# Character limit to put the reason of AFK. Players with "cp.afk.bypasslimit" will be ignored.
afk-reason-character-limit: 64
afk-auto: 300
afk-suffix: '&7&oAFK'
